pipeline {
    agent any
    stages {
        stage('Build Image') {
            steps {
                sshPublisher(
                    publishers: [
                    sshPublisherDesc(
                        configName: 'myserver',
                        transfers: [
                        sshTransfer(
                            excludes: '',
                            execCommand: '''
                                set -ex && cd /home/app && rm -rf jenkinstest && \
                                git clone https://github.com/jayyangwenqiang/jenkinstest.git && \
                                cd jenkinstest/jenkins/ &&  mvn package -Dmaven.test.skip=true && docker build -t jenkinstest:v1.0 .
                            ''',
                        )
                    ],
                    verbose: true
                    )
                ]
                )
            }
        }

        stage('deploy') {
            steps {
                sshPublisher(
                    publishers: [
                    sshPublisherDesc(
                        configName: 'myserver',
                        transfers: [
                        sshTransfer(
                            excludes: '',
                            execCommand: '''
                                set -ex && cd jenkinstest/jenkins && docker-compose up -d
                            ''',
                        )
                    ],
                    verbose: true
                    )
                ]
                )
            }
        }
    }

    post {
        always {
            println "构建.."
        }

        success {
            echo '发布成功'
        }
        unstable {
            echo '不稳定'
        }
        failure {
            echo '发布失败！'
        }
        changed {
            echo '项目变更'
        }
    }
}